# Conda environment file used by Github's continuous integration (CI) tools
# when building the jupyter book for publishing online. 
name: 25f-stats-ci
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.13
  # Scientific python
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  - nc-time-axis
  - flox
  # Jupyter
  - jupyter-book
  - ipykernel
  # Plotting
  - matplotlib 
  - hvplot
  - panel
  - jupyter_bokeh
  # Misc.
  - pooch  # For downloading datasets from web
